
spring:
  application:
    name: dubbo-demo-consumer
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  redis:
    host: 172.31.183.175
    port: 6379
dubbo:
  scan:
    base-packages: io.kimmking.dubbo.demo.consumer
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181