CREATE DATABASE IF NOT EXISTS mall_0;

CREATE DATABASE IF NOT EXISTS mall_1;

USE mall_0;

CREATE TABLE TB_MALL_ORDER_0 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_1 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_2 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_3 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_4 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_5 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_6 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_7 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_8 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_9 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_10 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_11 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_12 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_13 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_14 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_15 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;


USE mall_1;
CREATE TABLE TB_MALL_ORDER_0 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_1 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_2 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_3 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_4 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_5 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_6 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_7 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_8 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_9 (
                                 Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                 OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                 PayTime BIGINT COMMENT '支付时间',
                                 DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                 ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                 OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                 Buyer BIGINT NOT NULL COMMENT '下单用户',
                                 Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                 CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                 CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                 CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                 UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                 KEY `IDX_BUYER` (Buyer),
                                 KEY `IDX_ORDER_TIME` (OrderTime),
                                 KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_10 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_11 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_12 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_13 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_14 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;
CREATE TABLE TB_MALL_ORDER_15 (
                                  Id BIGINT NOT NULL PRIMARY KEY COMMENT '订单id, 先不自增, 以防分库分表',
                                  OrderTime BIGINT NOT NULL COMMENT '下单时间',
                                  PayTime BIGINT COMMENT '支付时间',
                                  DiscountAmount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
                                  ActualPrice DECIMAL (10, 2) NOT NULL COMMENT '实付金额',
                                  OrderStatus TINYINT(4) NOT NULL DEFAULT '1' COMMENT '订单状态: 1-下单未支付, 2-下单已支付(待发货), 3-运输中, 4-已签收, 5-已完成, 6-拒收, 7-申请退货, 8-退货运输中, 9-退货已签收',
                                  Buyer BIGINT NOT NULL COMMENT '下单用户',
                                  Remark VARCHAR(255) DEFAULT '' COMMENT '订单备注',
                                  CancelStatus TINYINT(1) NOT NULL DEFAULT 0 COMMENT '取消状态, 0-未取消, 1-取消中, 2-已取消',
                                  CancelTime BIGINT NOT NULL DEFAULT 0 COMMENT '取消时间',
                                  CreateTime BIGINT NOT NULL COMMENT '记录创建时间',
                                  UpdateTime BIGINT NOT NULL COMMENT '记录更新时间',
                                  KEY `IDX_BUYER` (Buyer),
                                  KEY `IDX_ORDER_TIME` (OrderTime),
                                  KEY `IDX_PAY_TIME` (PayTime)
)  DEFAULT CHARACTER SET     utf8mb4;

