DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
    Id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    StudentNo BIGINT NOT NULL,
    Name VARCHAR(10) NOT NULL DEFAULT ''
)

INSERT INTO STUDENT (StudentNo, Name) VALUES (20220101, '小明'), (20220102, '小红');